import './globals.css'
import { Inter, Mulish } from 'next/font/google'
import Header from './components/Header'
 
const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body >
      <Header/>
      {children}</body>
    </html>
  )
}
